# Generated by Django 5.0.6 on 2024-06-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_worldcities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Worldcities',
        ),
    ]
