# Generated by Django 5.0.6 on 2024-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_delete_worldcities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worldcities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'worldcities',
                'managed': False,
            },
        ),
    ]
